export interface TickerMapping {
  [key: string]: string;
}

export const TICKER_MAPPINGS: TickerMapping = {
  btc: 'btcusdt',
  bitcoin: 'btcusdt',
  btcusdt: 'btcusdt',
  eth: 'ethusdt',
  ethereum: 'ethusdt',
  ethusdt: 'ethusdt',
  bnb: 'bnbusdt',
  binance: 'bnbusdt',
  bnbusdt: 'bnbusdt',
  xrp: 'xrpusdt',
  ripple: 'xrpusdt',
  xrpusdt: 'xrpusdt',
  ada: 'adausdt',
  cardano: 'adausdt',
  adausdt: 'adausdt',
  sol: 'solusdt',
  solana: 'solusdt',
  solusdt: 'solusdt',
  doge: 'dogeusdt',
  dogecoin: 'dogeusdt',
  dogeusdt: 'dogeusdt',
  dot: 'dotusdt',
  polkadot: 'dotusdt',
  dotusdt: 'dotusdt',
  matic: 'maticusdt',
  polygon: 'maticusdt',
  maticusdt: 'maticusdt',
  avax: 'avaxusdt',
  avalanche: 'avaxusdt',
  avaxusdt: 'avaxusdt',
  link: 'linkusdt',
  chainlink: 'linkusdt',
  linkusdt: 'linkusdt',
  uni: 'uniusdt',
  uniswap: 'uniusdt',
  uniusdt: 'uniusdt',
  ltc: 'ltcusdt',
  litecoin: 'ltcusdt',
  ltcusdt: 'ltcusdt',
  atom: 'atomusdt',
  cosmos: 'atomusdt',
  atomusdt: 'atomusdt',
  etc: 'etcusdt',
  'ethereum classic': 'etcusdt',
  etcusdt: 'etcusdt',
  xlm: 'xlmusdt',
  stellar: 'xlmusdt',
  xlmusdt: 'xlmusdt',
  algo: 'algousdt',
  algorand: 'algousdt',
  algousdt: 'algousdt',
  vet: 'vetusdt',
  vechain: 'vetusdt',
  vetusdt: 'vetusdt',
  icp: 'icpusdt',
  'internet computer': 'icpusdt',
  icpusdt: 'icpusdt',
  fil: 'filusdt',
  filecoin: 'filusdt',
  filusdt: 'filusdt',
  trx: 'trxusdt',
  tron: 'trxusdt',
  trxusdt: 'trxusdt',
};
